import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";
import dynamic from "next/dynamic";
import { Toaster } from "@/components/ui/toaster";
import { Suspense } from "react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

// Carregamento dinâmico do Sidebar para evitar problemas de SSR
const DynamicSidebar = dynamic(
  () => import("@/components/layout/sidebar/Sidebar"),
  {
    ssr: false,
  }
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${inter.variable} font-sans antialiased flex max-h-screen overflow-hidden text-primary w-full h-full`}
      >
        <Providers>
          <Suspense fallback={<div>Loading...</div>}>
            <DynamicSidebar />
            <main className="flex-grow overflow-auto">{children}</main>
          </Suspense>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
